name: flutter_programming_question_collection
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  flutter_onboarding_slider: ^1.0.11
  shared_preferences: ^2.3.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  permission_handler: ^11.3.1
  simple_app_cache_manager: ^0.0.4
  version_tracker: ^2.4.1
  google_fonts: ^6.1.0
  rating_dialog: ^2.0.4
  easy_localization: ^3.0.5
  store_redirect: ^2.0.2
  share_plus: ^10.0.2
  flutter_native_splash: ^2.4.1
  flutter_spinkit: ^5.2.1
  equatable: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  connectivity_plus: ^5.0.2
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  emailjs: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen_runner: ^5.3.0
  build_runner: ^2.4.11
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: "assets/app-original.png"
  adaptive_icon_foreground: "assets/app-original.png"
  adaptive_icon_background: "#1398C3"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/app.png

  android_12:
    image: assets/app.png
    icon_background_color: "#ffffff"
    image_dark: assets/app.png
    icon_background_color_dark: "#121212"

flutter:
  uses-material-design: true

  assets:
    - assets/app.png
    - assets/app-original.png
    - assets/svg/
    - assets/introduction/
    - assets/translations/
    - assets/questions/en/
    - assets/questions/ru/
    - assets/questions/tr/
    - assets/icons/
    - .env

  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
