// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OXFtTuBff-y3lDEURv8ANVlrVl5TGNs',
    appId: '1:717722462722:web:201cc42b87f3dfbdc1951b',
    messagingSenderId: '717722462722',
    projectId: 'interview-helper-e1137',
    authDomain: 'interview-helper-e1137.firebaseapp.com',
    storageBucket: 'interview-helper-e1137.appspot.com',
    measurementId: 'G-ZSSKGE3R1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfM3zq1cvHj6RPJisQjExT3mFyBiifOu0',
    appId: '1:717722462722:android:af34e5734dcffa42c1951b',
    messagingSenderId: '717722462722',
    projectId: 'interview-helper-e1137',
    storageBucket: 'interview-helper-e1137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbA7C52m6iMtpqukXaq7AbR0lUwFMVvig',
    appId: '1:717722462722:ios:c7bc7660dcee26b5c1951b',
    messagingSenderId: '717722462722',
    projectId: 'interview-helper-e1137',
    storageBucket: 'interview-helper-e1137.appspot.com',
    iosBundleId: 'com.example.flutterProgrammingQuestionCollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbA7C52m6iMtpqukXaq7AbR0lUwFMVvig',
    appId: '1:717722462722:ios:c7bc7660dcee26b5c1951b',
    messagingSenderId: '717722462722',
    projectId: 'interview-helper-e1137',
    storageBucket: 'interview-helper-e1137.appspot.com',
    iosBundleId: 'com.example.flutterProgrammingQuestionCollection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0OXFtTuBff-y3lDEURv8ANVlrVl5TGNs',
    appId: '1:717722462722:web:f863c3e1db8306ccc1951b',
    messagingSenderId: '717722462722',
    projectId: 'interview-helper-e1137',
    authDomain: 'interview-helper-e1137.firebaseapp.com',
    storageBucket: 'interview-helper-e1137.appspot.com',
    measurementId: 'G-BQ21MHD69H',
  );
}
